// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Data;

#nullable disable

namespace StudentManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Student", b =>
                {
                    b.Property<string>("StudentNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgrammeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("YearLevel")
                        .HasColumnType("int");

                    b.HasKey("StudentNumber");

                    b.HasIndex("FacultyId");

                    b.HasIndex("ProgrammeId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyId"));

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            FacultyId = 1,
                            FacultyName = "Natural and Agricultural Sciences"
                        },
                        new
                        {
                            FacultyId = 2,
                            FacultyName = "Health Sciences"
                        },
                        new
                        {
                            FacultyId = 3,
                            FacultyName = "Education"
                        },
                        new
                        {
                            FacultyId = 4,
                            FacultyName = "Law"
                        },
                        new
                        {
                            FacultyId = 5,
                            FacultyName = "Economic and Management Sciences"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Programme", b =>
                {
                    b.Property<int>("ProgrammeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgrammeId"));

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("ProgrammeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProgrammeId");

                    b.HasIndex("FacultyId");

                    b.ToTable("Programmes");

                    b.HasData(
                        new
                        {
                            ProgrammeId = 1,
                            FacultyId = 1,
                            ProgrammeName = "BSc Information Technology"
                        },
                        new
                        {
                            ProgrammeId = 2,
                            FacultyId = 1,
                            ProgrammeName = "BSc Computer Science"
                        },
                        new
                        {
                            ProgrammeId = 3,
                            FacultyId = 1,
                            ProgrammeName = "BSc Mathematics"
                        },
                        new
                        {
                            ProgrammeId = 4,
                            FacultyId = 2,
                            ProgrammeName = "Bachelor of Nursing"
                        },
                        new
                        {
                            ProgrammeId = 5,
                            FacultyId = 2,
                            ProgrammeName = "Physiotherapy"
                        },
                        new
                        {
                            ProgrammeId = 6,
                            FacultyId = 3,
                            ProgrammeName = "BEd Foundation Phase"
                        },
                        new
                        {
                            ProgrammeId = 7,
                            FacultyId = 4,
                            ProgrammeName = "LLB"
                        },
                        new
                        {
                            ProgrammeId = 8,
                            FacultyId = 5,
                            ProgrammeName = "BCom Accounting"
                        },
                        new
                        {
                            ProgrammeId = 9,
                            FacultyId = 5,
                            ProgrammeName = "BCom Economics"
                        });
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Programme", "Programme")
                        .WithMany("Students")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Programme", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Faculty", "Faculty")
                        .WithMany("Programmes")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Faculty", b =>
                {
                    b.Navigation("Programmes");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Programme", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
